# Continuous Deployment
#
# References:
#
# - https://docs.github.com/en/actions/guides/building-and-testing-nodejs
# - https://jestjs.io/docs/cli#--ci
# - https://octokit.github.io/rest.js/#pagination

---
name: Continuous Deployment
on:
  pull_request_review:
    types: [submitted]
jobs:
  continuous-deployment:
    if: |
      ${{ startsWith(github.ref, 'ref/heads/releases/') }} &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    env:
      PAT_GPR_FLDV: ${{ secrets.PAT_GPR }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          always-auth: true
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@flex-development'
      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${PAT_GPR_FLDV}
      - name: Run test suites
        run: TERM=xterm-256color yarn test --ci
      - name: Get release info
        uses: actions/github-script@v4
        id: release
        with:
          script: core.setOutput('t', context.ref.split('release/')[1])
      - name: Publish GitHub Release
        uses: actions/github-script@v4
        with:
          script: |
            const opts = github.repos.listReleases(context.repo)
            const releases = await github.paginate(opts)
            const version = context.ref.split('release/autoreview@')[1]

            releases.forEach(({ draft, id: release_id, tag_name: tag }) => {
              tag === `v${version}` && draft && github.repos.updateRelease({
                ...context.repo,
                draft: false,
                release_id
              })
            })
      - name: Automerge pull request
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_COMMIT_MESSAGE: 'merge: release ${{ steps.release.outputs.t }}'
          MERGE_METHOD: merge
      - name: Merge next into main
        uses: devmasx/merge-branch@v1.3.1
        with:
          github_token: ${{ github.token }}
          from_branch: next
          target_branch: main
          type: now
      - name: Close issues with status:merged label
        uses: bdougie/close-issues-based-on-label@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          LABEL: status:merged
      - name: Add status:released label to closed issues
        uses: actions/github-script@v4
        with:
          script: |
            const opts = github.issues.listForRepo(context.issue)
            const issues = await github.paginate(opts)

            issues.forEach(issue => {
              issue.labels.forEach(({ name, number: issue_number }) => {
                label.name === 'status:merged' && github.issues.addLabels({
                  ...context.repo,
                  issue_number,
                  labels: ['status:released']
                })
              })
            })
